name: Convert Templates

on:
  workflow_dispatch:

jobs:
  genthemes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Run Script
        run: |
          chmod +x .github/scripts/templates/gentemplates.main.kts 
          .github/scripts/templates/gentemplates.main.kts

      - name: Commit and push changes
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update Templates"
          git push
